import { Robot } from "./games/robot.js";
import { Factory } from "./games/factory.js";
import { Ricochet } from "./games/ricochet.js";
import { Diner } from "./games/diner.js";
import { Drill } from "./games/drill.js";
import { Harbor } from "./games/harbor.js";
import { Train } from "./games/train.js";
import { Mech } from "./games/mech.js";
import { Worlds } from "./games/worlds.js";
import { Cleanup } from "./games/cleanup.js";
export const GAMES = [
  {
    id: "robot",
    name: "Robot Wreckers",
    tag: "BREAK IT BEAUTIFULLY",
    genre: "Tactical puzzle",
    color: "#3d99b4",
    accent: "#ffce59",
    Game: Robot,
    desc: "Load your cannons. Break the supports. Bring the whole machine down.",
    verb: "Dismantle",
    unit: "Machine",
    upgrade: {
      key: "insight",
      name: "Workshop insight",
      desc: "+1 inspection charge per machine",
      icon: "eye",
    },
    biomes: [
      "Tin Yard",
      "Clockwork Bay",
      "Copperworks",
      "Neon Foundry",
      "Sky Machines",
      "Titan Vault",
    ],
  },
  {
    id: "factory",
    name: "Factory Under Siege",
    tag: "BUILD. FEED. DEFEND.",
    genre: "Factory defense",
    color: "#5e8c89",
    accent: "#f7bd5c",
    Game: Factory,
    desc: "Build a supply line that can actually feed your guns. Two lanes. Tough choices.",
    verb: "Defend",
    unit: "Outpost",
    upgrade: {
      key: "supplies",
      name: "Starter shipment",
      desc: "+5 starting gold per level",
      icon: "box",
    },
    biomes: [
      "Copper Yard",
      "Dust Frontier",
      "Frostworks",
      "Iron Coast",
      "Red Furnace",
      "Last Assembly",
    ],
  },
  {
    id: "ricochet",
    name: "Ricochet Raiders",
    tag: "MAKE EVERY ANGLE COUNT",
    genre: "Aim & adventure",
    color: "#6c9e70",
    accent: "#eec65e",
    Game: Ricochet,
    desc: "Bank shots around shields. Blow up the room. Build your perfect volley.",
    verb: "Raid",
    unit: "Vault",
    upgrade: {
      key: "recovery",
      name: "Field recovery",
      desc: "+1 heart restored after rooms 2 and 4, up to full health",
      icon: "heart",
    },
    biomes: [
      "Moss Vault",
      "Sunken Temple",
      "Crystal Rooms",
      "Ash Citadel",
      "Moon Keep",
      "Golden Tomb",
    ],
  },
  {
    id: "diner",
    name: "Monster Diner",
    tag: "GOOD FOOD. BIG APPETITES.",
    genre: "Kitchen rush",
    color: "#d58877",
    accent: "#ffe3a4",
    Game: Diner,
    desc: "Cook, serve, and keep your strange little guests smiling through the rush.",
    verb: "Open",
    unit: "Venue",
    upgrade: {
      key: "welcome",
      name: "Warm welcome",
      desc: "+1 second of guest patience per level",
      icon: "heart",
    },
    biomes: [
      "Moss & Mug",
      "Moonlight Diner",
      "Dragon Grill",
      "Cloud Café",
      "Cove Kitchen",
      "Grand Banquet",
    ],
  },
  {
    id: "drill",
    name: "Drill Heist",
    tag: "ONE MORE GOLD VEIN?",
    genre: "Mining expedition",
    color: "#a980a1",
    accent: "#f6ce62",
    Game: Drill,
    desc: "Find the richest route underground. Bank your cargo before the cave closes.",
    verb: "Dig",
    unit: "Stratum",
    upgrade: {
      key: "capacity",
      name: "Cargo rack",
      desc: "+3 cargo capacity per level",
      icon: "box",
    },
    biomes: [
      "Soft Earth",
      "Copper Bed",
      "Crystal Fault",
      "Obsidian Reach",
      "Deep Ruins",
      "Starstone",
    ],
  },
  {
    id: "harbor",
    name: "Rescue Harbor",
    tag: "A CLEAR WAY HOME",
    genre: "Boat puzzle",
    color: "#50b5c5",
    accent: "#fff0af",
    Game: Harbor,
    desc: "Untangle the boats, follow their arrows, and bring every passenger home.",
    verb: "Rescue",
    unit: "Harbor",
    upgrade: {
      key: "patience",
      name: "Harbor training",
      desc: "+1 blocked-move allowance per level",
      icon: "shield",
    },
    biomes: [
      "Sunny Inlet",
      "Turtle Cove",
      "Coral Crossing",
      "Moonlight Bay",
      "Storm Channel",
      "Pearl Island",
    ],
  },
  {
    id: "train",
    name: "Last Train",
    tag: "YOUR BUILD. YOUR JOURNEY.",
    genre: "Convoy survival",
    color: "#ac8569",
    accent: "#f4ce77",
    Game: Train,
    desc: "Refit your wagons. Choose your route. Keep the express alive.",
    verb: "Depart",
    unit: "Route",
    upgrade: {
      key: "spares",
      name: "Spare parts",
      desc: "+5 starting refit scrap per level",
      icon: "gear",
    },
    biomes: [
      "Prairie Line",
      "Copper Canyon",
      "Pine Express",
      "Snowbound",
      "Ember Route",
      "End of the Line",
    ],
  },
  {
    id: "mech",
    name: "Scrap Mech",
    tag: "BUILT BY YOU. DRIVEN BY YOU.",
    genre: "Build & battle",
    color: "#7588ba",
    accent: "#8ee1ed",
    Game: Mech,
    desc: "Snap on weapons and batteries. Take your creation into the scrapyard arena.",
    verb: "Assemble",
    unit: "League",
    upgrade: {
      key: "spares",
      name: "Salvage stock",
      desc: "+5 starting build scrap per level",
      icon: "gear",
    },
    biomes: [
      "Rust Ring",
      "Neon Docks",
      "Sand Pit",
      "Frost Circuit",
      "Core Arena",
      "Champions Yard",
    ],
  },
  {
    id: "worlds",
    name: "Tiny Worlds",
    tag: "MAKE A LITTLE PLACE YOURS",
    genre: "Creative restoration",
    color: "#ab9ab5",
    accent: "#ffe5b0",
    Game: Worlds,
    desc: "Sweep, repair, and furnish a miniature place. Then watch it come alive.",
    verb: "Restore",
    unit: "Project",
    upgrade: {
      key: "brush",
      name: "Soft wide brush",
      desc: "+4 pixels of cleaning reach per level",
      icon: "spark",
    },
    biomes: [
      "The Bakery",
      "Garden Nook",
      "Little Workshop",
      "Teahouse",
      "Sunroom",
      "Lakeside Studio",
    ],
  },
  {
    id: "cleanup",
    name: "Pocket Cleanup",
    tag: "A LITTLE MESS. A BIG PAYOFF.",
    genre: "Collection adventure",
    color: "#82ad86",
    accent: "#f8d374",
    Game: Cleanup,
    desc: "Vacuum the clutter, choose the right attachments, and restore a little district.",
    verb: "Clean",
    unit: "Job",
    upgrade: {
      key: "capacity",
      name: "Bigger bag",
      desc: "+2 bag capacity per level",
      icon: "box",
    },
    biomes: [
      "Pocket Park",
      "The Workshop",
      "Sunny Plaza",
      "Seaside Walk",
      "Moon Market",
      "Festival Square",
    ],
  },
];
export const byId = (id) => GAMES.find((g) => g.id === id);
